### ISSUE TITLE
Add note from Notes page

### ISSUE THREAD

**Issue by lrasmus** [StatTag/StatWrap#140]
Request:

"Can we add notes from the notes page itself?  I went there to add a general one and realized there wasn’t a plus button."

**Comment by vr-varad** [comment]
@lrasmus is this issue being worked upon?

**Comment by lrasmus** [comment]
@vr-varad - thanks for expressing interest!  Let me get some input from the team on exactly how we want this to work, and I'll update with details.  If this looks interesting to you, happy to let you contribute.

**Comment by vr-varad** [comment]
Ya looking forward to contribute to it;)

**Comment by lrasmus** [comment]
I think for now, when adding a note from the Notes page this would be a note specifically for the project itself.  Adding notes for other types of objects would require the context of that object, which I think is better done from where notes are added now (e.g., only adding notes for assets from the assets view).

**Comment by AdiAkhileshSingh15** [comment]
I can happily take this task up, if you can assign it to me.
