### ISSUE TITLE
ADD ISSUE TEMPLATE for creation of new issues 

### ISSUE THREAD

**Issue by vinfinity7** [StatTag/StatWrap#151]
Summary:
I propose the addition of an issue template for the creation of new issues within the project. This will ensure that contributors provide consistent and essential information, streamlining the issue resolution and feature development processes.

Details:
Currently, some issues lack standardized information, leading to delays in addressing them. An issue template will help contributors provide necessary context, steps to reproduce, and other crucial details, making it easier for maintainers to understand and act on issues promptly.

Benefits:

Clarity and Consistency: Standardized information for all issues.
Efficiency: Faster issue resolution and feature development.
Resource Optimization: Better understanding of urgency and impact.
Enhanced Collaboration: Clear expectations for contributors.
Project Management: Improved tracking and prioritization of issues.
User-Friendly Experience: Positive contribution experience for all.
Next Steps:

Discuss and agree on the specific details to include in the template.
Implement the template in the repository.
Communicate the availability and usage of the template to contributors.

**Comment by vr-varad** [comment]
@lrasmus could i work on it?

**Comment by lrasmus** [comment]
Thank you for your interest in the project and for this suggestion.  While I know some projects do use templates, we prefer an open approach for issues.  We may get a mix of requests for information, asking about the UI, request for new features, bug fixes, etc.  We don't want people to feel constrained to fill out a templated issue, especially if things don't apply to their reason for opening the issue.

**Comment by vinfinity7** [comment]
Hey @lrasmus , just a friendly heads-up to check your email when you get a chance. It's regarding something that might interest you. Thanks! @misrasaksham9@gmail.com
