### ISSUE TITLE
Add a PULL REQUEST TEMPLATE for the project 

### ISSUE THREAD

**Issue by vinfinity7** [StatTag/StatWrap#152]
**Description:**

**Issue:**
Currently, the project lacks pull request templates, which can lead to inconsistencies and inefficiencies in the contribution process. Pull request templates offer a standardized format for contributors, ensuring that vital information is provided upfront and facilitating a smoother review process for both contributors and reviewers.

**Objective:**
The objective of implementing pull request templates is to:
- Offer contributors guidance on the required information for their pull requests, such as a summary of changes, related issues, and testing procedures.
- Maintain consistency across pull requests, simplifying the review process for reviewers and enhancing comprehension of the changes.
- Streamline the review process by minimizing the need for extensive communication to gather necessary details from contributors.

**Expected Outcome:**
Upon implementation, pull request templates will contribute to a more efficient and organized contribution process, resulting in quicker merge times and higher-quality contributions overall.

**Comment by vinfinity7** [comment]
@lrasmus Kindly look into this too 👍

**Comment by vr-varad** [comment]
@lrasmus i would like to work upon it

**Comment by lrasmus** [comment]
Thank you for this suggestion as well.  Similar to #151, we also recognize that some projects benefit from a PR template, however we don't feel that this is a good fit for our project as it may overly-formalize the process.  If there is a PR, we are happy to collaboratively communicate with the developer to discuss or ask for clarifications (meaning, it is not an issue for the core maintainers to have to follow up).
