### ISSUE TITLE
+/- zoom control buttons for Workflow view

### ISSUE THREAD

**Issue by lrasmus** [StatTag/StatWrap#166]
The Workflow tab - specifically the Dependency Graph view - allows the user to zoom in and out on the generated graph using the scroll wheel of the mouse (this was a feature already enabled in the EChart library we use).

It's not apparent to users that they have the ability to zoom in and out.  We want to support the mouse wheel zooming, but also have visible buttons (suggested to use + and -) to also control the zooming.

![image](https://github.com/StatTag/StatWrap/assets/967970/30bff64a-253a-4fe8-8216-cb2464aedddc)

**Comment by Abhijay007** [comment]
@lrasmus can I work on this issue?

**Comment by lrasmus** [comment]
@Abhijay007 absolutely!  Thank you!  Going to assign it to you so folks know it's "taken", but no obligation

**Comment by Abhijay007** [comment]
Thanks @lrasmus for the assignment, I will soon open a PR around the same.
