### ISSUE TITLE
Eslint is failing for pre commit hooks 

### ISSUE THREAD

**Issue by utnim2** [StatTag/StatWrap#169]
Eslint is failing for pre commit hook and `lint-fix` is not working too

**Comment by lrasmus** [comment]
Thank you!  I need to look at adjusting eslint config.  I have seen this myself, and many "errors" are false positives (in how we want our coding standard to work).

**Comment by utnim2** [comment]
@lrasmus can i work on it?

**Comment by jayantpranjal0** [comment]
Hii, @lrasmus I found out that typescript wasn't mentioned as an dependency in the package.json file. Should I add a commit with that?

**Comment by jayantpranjal0** [comment]
@lrasmus

**Comment by lrasmus** [comment]
Thank you @jayantpranjal0!  Yes, please feel free to tackle this.  Some of this may require me to go over what we want for the linting rules, but happy to have your contribution about including typescript.

**Comment by jayantpranjal0** [comment]
Thanks, I am making a PR with this issue. I think we could prepare some documentation regarding linting rules and then I could work on that.

**Comment by AdiAkhileshSingh15** [comment]
@Abhijay007 @lrasmus I was trying to reproduce the error for `yarn lint-fix` , but, it seems it ran just fine for me, did some useful linting of the code, precisely 60 files with minor warnings and errors, which can be resolved by adjusting the eslint config as we want, in my opinion. 

Though this failing for pre-commit hooks part, I have experienced earlier, but probably won't from now as I have removed my pre-commit hooks files earlier for some reason (while updating husky) . So, I won't be able to reproduce it for now, which am also confused how-to without making useless commits ( do you guys add some code for exiting the commit at the end of your pre-commit files 🤔  or else how do you test these pre-commit hooks).

**Comment by Abhijay007** [comment]
> @lrasmus I was trying to reproduce the error for `yarn lint-fix` , but, it seems it ran just fine for me, did some useful linting of the code, precisely 60 files with minor warnings and errors, which can be resolved by adjusting the eslint config as we want, in my opinion.
> 
> Though this failing for pre-commit hooks part, I have experienced earlier, but probably won't from now as I have removed my pre-commit hooks files earlier for some reason (while updating husky) . So, I won't be able to reproduce it for now, which am also confused how-to without making useless commits ( do you guys add some code for exiting the commit at the end of your pre-commit files 🤔 or how else do you test these pre-commit hooks).

@AdiAkhileshSingh15 are you asking how to manually run the pre-commit hooks for checking its results?

**Comment by AdiAkhileshSingh15** [comment]
@Abhijay007 Thanks for responding, but I got my answer. There's a shell script file in the hooks folder which I didn't know about earlier as I removed the my hooks folder while updating husky.

**Comment by AdiAkhileshSingh15** [comment]
But, the `yarn lint-fix` is still working just fine for me, so, if @lrasmus you can brief me about that. What exactly is it that's not working in it, the way you want linting to be done or just the linting itself?

**Comment by jayantpranjal0** [comment]
@AdiAkhileshSingh15 The syntax error you mentioned in the PR: https://github.com/StatTag/StatWrap/pull/184 fixes this issue.

**Comment by lrasmus** [comment]
Thank you @jayantpranjal0 for your interest in this.  @AdiAkhileshSingh15 has also expressed interest and has some time now to investigate.  I'm going to reassign, but please feel free to share here anything you found.
