### ISSUE TITLE
Display log timestamps in user's timezone

### ISSUE THREAD

**Issue by lrasmus** [StatTag/StatWrap#172]
We use the `winston` logger for all actions in StatWrap, and have accepted the default behavior for timestamps to be recorded in UTC.  When we display the project log to the user, the timestamps are in UTC, which could be confusing.  In the example below, the log actions took place at 4:18pm Central time and 2:57pm Central time, and should be displayed to the user in their current time zone.

![image](https://github.com/StatTag/StatWrap/assets/967970/1be5968f-08a3-472a-8f74-c529428187c4)

Formatting of the timestamps in the Project Log list does not need to explicitly show the timezone for each entry (meaning, we don't need to have "Central Time" or "CST" with every entry).  The user is more inclined to assume the date and times shown are localized for them.

**Comment by Abhijay007** [comment]
@lrasmus can I work on this issue?

**Comment by lrasmus** [comment]
Thank you @Abhijay007 !

**Comment by Abhijay007** [comment]
Thanks for assignment @lrasmus , I will soon open are PR for the same
