### ISSUE TITLE
Husky pre-commit hook not called

### ISSUE THREAD

**Issue by lrasmus** [StatTag/StatWrap#195]
Recently noticed that the husky pre-commit hook (to run lint-staged) was no longer being called.  This is due to changes in how v9 of husky works.

**Comment by lrasmus** [comment]
To reproduce:

1. Make a change with an invalid style issue that the linter would catch
2. Add the changed file to git stage
3. Run `git commit`
4. No call is made to invoke `lint-staged`

**Comment by Abhijay007** [comment]
Can I work on this issue ?

**Comment by Abhijay007** [comment]
*sure will review it, ignore above message
