### ISSUE TITLE
StatWrap web presence

### ISSUE THREAD

**Issue by lrasmus** [StatTag/StatWrap#64]
We need a location for users to find information about StatWrap

Related to #58 - needing a place to download.  These do not need to be the same location (StatTag isn't), but could be to simplify.

**Comment by Abhijay007** [comment]
@lrasmus  this issue is also seems to be  already resolved with this: https://sites.northwestern.edu/statwrap site

**Comment by lrasmus** [comment]
Good catch again, thanks @Abhijay007!
